# Copyright (C) 2012  TEA, the ebook alternative <http://www.tea-ebook.com/>
# 
# This file is part of TeaBook Open Reader
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3.0 of the License.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# 
# An additional permission has been granted as a special exception 
# to the GNU General Public Licence. 
# You should have received a copy of this exception. If not, see 
# <https://github.com/TEA-ebook/teabook-open-reader/blob/master/GPL-3-EXCEPTION>.



:gaston:
  security:
    # When enabled, we sandbox the JS in ebooks
    # by using the HTML5 sandbox attribute on iframes
    # (without the allow-same-origin flag).
    #
    # Currently, you don't want to enable it since the
    # reader will render blank pages, but it can evolves.
    # See https://bugs.webkit.org/show_bug.cgi?id=90613
    sandbox: false

    # If this flag is set to false, the javascript in ebooks
    # will be pruned during the import.
    allow_js: true
